LIBS=-lpthread -lsfml-graphics -lsfml-window -lsfml-system
HEADERS=../sendDataFormat.hpp
SOURCES=../sendDataFormat.cpp simpleSFMLclient.cpp

simple_client: $(SOURCES) $(HEADERS)
	g++ -o simple_client $(SOURCES) $(LIBS) -I.