
name: Tests

on:
  push:
    branches: [ optimization ]
  pull_request:
    branches: [ optimization ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: cd build && ./tests/AgarioServer_tst