
name: C++ tests

on:
  push:
    branches: [ optimization ]
  pull_request:
    branches: [ optimization ]

jobs:
  build:
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    - name: CMake Configure
      run: mkdir build && cd build && cmake ..
    - name: CMake Build
      run: |
        cd build
        make
    - name: Run Test
      run: cd build && ./tests/AgarioServer_tst
